# Generated by Django 4.2.5 on 2023-10-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Perfil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensajeContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "correo",
                    models.EmailField(
                        max_length=100, verbose_name="Correo Electrónico"
                    ),
                ),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Envío"
                    ),
                ),
                ("leido", models.BooleanField(default=False, verbose_name="Leído")),
            ],
        ),
    ]
