# Generated by Django 4.2.5 on 2023-10-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Perfil", "0002_mensajecontacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="direccion",
            name="comentarios",
            field=models.TextField(max_length=300, verbose_name="Comentarios"),
        ),
    ]
