# Generated by Django 4.2.5 on 2023-10-17 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Perfil", "0003_alter_direccion_comentarios"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Tienda", "0002_alter_producto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_total",
                    models.PositiveIntegerField(verbose_name="Monto Total"),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Entregado", "Entregado"),
                            ("En Camino", "En Camino"),
                            ("Cancelado", "Cancelado"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Referencia"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "direccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Perfil.direccion",
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "productos",
                    models.ManyToManyField(
                        related_name="pedidos",
                        to="Tienda.producto",
                        verbose_name="Productos",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
    ]
